export const TOOL_ITEMS={
    LINE:"LINE",
    RECTANGLE:"RECTANGLE",
    CIRCLE:"CIRCLE",
    ARROW:"ARROW",
    BRUSH:"BRUSH",
    ERASER:"ERASER",
    TEXT:"TEXT",
    UNDO:"UNDO",
    REDO:"REDO",
};

export const TOOL_ACTION_TYPES={
    NONE:"NONE",
    DRAWING:"DRAWING",
    ERASING:"ERASER",
    UP:"UP",
    WRITING:"WRITING",
    DOWN:"DOWN",
};
export const BOARD_ACTIONS={
    CHANGE_TOOL:"CHANGE_TOOL",
    DRAW_DOWN:"DRAW_DOWN",
    DRAW_MOVE:"DRAW_MOVE",
    DRAW_UP:"DRAW_UP",
    ERASER:"ERASER",
    DRAWING:"DRAWING",
    WRITING:"WRITING",
    UNDO:"UNDO",
    REDO:"REDO",
};

export const COLORS ={
    BLACK:"#000000",
    RED:"#ff0000",
    GREEN:"#0000ff",
    BLUE:"#00ff00",
    YELLOW:"#ffff00",
    ORANGE:"#ffa500",
    WHITE:"#ffffff",
    PURPLE:"#800080",
}

export const TOOLBOX_ACTIONS={
    CHANGE_STROKE:"CHANGE_STROKE",
    CHANGE_FILL:"CHANGE_FILL",
    CHANGE_SIZE:"CHANGE_SIZE",
};

export const FILL_TOOL_TYPES=[TOOL_ITEMS.RECTANGLE,TOOL_ITEMS.CIRCLE];
export const STROKE_TOOL_TYPES=[TOOL_ITEMS.LINE,TOOL_ITEMS.ARROW,
    TOOL_ITEMS.BRUSH,TOOL_ITEMS.RECTANGLE,TOOL_ITEMS.CIRCLE,TOOL_ITEMS.TEXT];

export const ARROW_LENGTH=20;

export const SIZE_TOOL_TYPES=[TOOL_ITEMS.LINE,TOOL_ITEMS.ARROW,TOOL_ITEMS.RECTANGLE,TOOL_ITEMS.CIRCLE,TOOL_ITEMS.BRUSH,TOOL_ITEMS.TEXT];

export const ELEMENT_ERASE_THRESHOLD=1;